### ISSUE TITLE
Using with SSR

### ISSUE THREAD

**Issue by golinmarq** [dai-shi/use-reducer-async#11]
Right now, I receive an error message that says 
`Abort Controller is not defined`

How do you use it with NextJS? Could you please gives us an example

**Comment by dai-shi** [comment]
Please use AbortController polyfill.
For example, https://www.npmjs.com/package/abort-controller
I haven't tried it before.
BTW, node15 have AbortController, so eventually nextjs will support it.

**Comment by momentosmagix** [comment]
Sure but where do I import this package?

**Comment by dai-shi** [comment]
I'm not very familiar with nextjs setup. If you add the polyfill in the file that raises an error, does it help?

**Comment by golinmarq** [comment]
Thanks, I added to my _app.js file and it worked
