### ISSUE TITLE
Async action calling another async action

### ISSUE THREAD

**Issue by rpmonteiro** [dai-shi/use-reducer-async#7]
1. React component dispatches async action
2. async action has some side effects, and dispatches another async action

Is it possible with this library, or will the async actions dispatched from within another async action be ignored?

**Comment by dai-shi** [comment]
It's not possible with this library. Or, it can be said it's not the scope of this library.

What I would probably do is something like this.

```js
const asyncTask1 = async (dispatch, arg1) => {
  ...
};

const asyncTask2 = async (dispatch, arg2) => {
  ...
  await asyncTask1(dispatch, arg1);
  ...
};

const asyncActionHandlers = {
  TASK1: ({ dispatch }) => async (action) => asyncTask1(dispatcy, action.arg1),
  TASK2: ({ dispatch }) => async (action) => asyncTask2(dispatcy, action.arg2),
};
```

Hope it helps.

----

On second thought, it should technically possible to support dispatching recursively. I lean to the simplicity and not to support it though.

**Comment by dai-shi** [comment]
https://github.com/dai-shi/react-tracked/issues/128#issuecomment-999365549

> I still don't understand why it's not possible.

@gabrielhpugliese It's technically possible. I don't feel like the recursion is good design (which can lead infinite loop). I might be wrong.

**Comment by dai-shi** [comment]
https://github.com/dai-shi/react-tracked/issues/128#issuecomment-999356164

> How would I dispatch an action that has an async side-effect if my request fail or is successful?

Hmm, my assumption was probably to extract such async function in advance and reuse it in action handlers. It should work, but now not sure DX-wise.

**Comment by gabrielhpugliese** [comment]
I think the main benefit would be the message passing and ability to follow it as separate side-effects instead of function calling, e.g. when you use something to track/log the actions in the console like a dev tools.

**Comment by dai-shi** [comment]
I'm getting convinced. At least two of you suggested this. So, probably, there's more benefits than concerns. Let's reopen this.
